name: blossomhub
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  image: ^3.0.1
  shared_preferences: ^2.0.0
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_svg: ^0.22.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/loading.svg
    - assets/on_boarding/first_pic.png
    - assets/on_boarding/second_pic.png
    - assets/on_boarding/third_pic.png
    - assets/placeholder_image.png
    - assets/f_flower.png
    - assets/s_flower.png
    - assets/t_flower.png
    - assets/fo_flower.png

